# nameOverride: dask
# fullnameOverride: dask

scheduler:
  name: scheduler
  image:
    repository: "daskdev/dask"
    tag: 1.1.0
    pullPolicy: IfNotPresent
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 8786
  resources: {}
     limits:
       cpu: 4
       memory: 18G
     requests:
       cpu: 2
       memory: 6G

webUI:
  name: webui
  servicePort: 80

worker:
  name: worker
  image:
    repository: "daskdev/dask"
    tag: 1.1.0
    pullPolicy: IfNotPresent
  replicas: 3
  aptPackages: >-
  default_resources:  # overwritten by resource limits if they exist
    #cpu: 1
    #memory: "3.75GiB"
  env:
     - name: EXTRA_CONDA_PACKAGES
       value: fastparquet pandas numba xarray -c conda-forge
     - name: EXTRA_PIP_PACKAGES
       value: cython six pyarrow gcsfs s3fs dask-ml dask-xgboost --upgrade
  resources: {}
     limits:
       cpu: 4
       memory: 8G
     requests:
       cpu: 2
       memory: 8G

jupyter:
  name: jupyter
  enabled: true
  image:
    repository: "daskdev/dask-notebook"
    tag: 1.1.0
    pullPolicy: IfNotPresent
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 80
  password: 'sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c'  # 'dask'
  env:
     - name: EXTRA_CONDA_PACKAGES
       value: fastparquet pandas numba xarray -c conda-forge
     - name: EXTRA_PIP_PACKAGES
       value: cython six pyarrow gcsfs s3fs dask-ml dask-xgboost --upgrade
  resources: {}
    # limits:
    #   cpu: 2
    #   memory: 6G
    # requests:
    #   cpu: 2
    #   memory: 6G
